### ISSUE TITLE
Comma Issue

### ISSUE THREAD

**Issue by sepehrsohrabii** [iSegaro/Subscription#1]
Hi Segaro,
Thank you for all your hard work.

There was an issue in the worker.js file in the below line, It replaces the commas between the config links however it shouldn't:
`const responseText = links.join('\n').replace(/,/g, '\n');`

So I changed it in the way that it just gets the commas at the end of each line as below and the problem has been fixed.
`const responseText = links.join('\n').replace(/,(?=\n|$)/g, '');`

**Comment by iSegaro** [comment]
Thanks
ممنون تغییر دادم. برنامه نویس نیستم داده بودم چت جی پی تی نوشته بودم برام ممنون از راهنماییت
